### ISSUE TITLE
我在win10上遇到一些问题

### ISSUE THREAD

**Issue by wmathor** [NightCatSama/NightCAT-ChatRoom#2]
跑是正常跑起来了，但是当我输入完信息，点击注册时，网页卡住了，不知道是怎么了

**Comment by NightCatSama** [comment]
注册接口调用了吗，控制台有报错吗

**Comment by wmathor** [comment]
![image](https://user-images.githubusercontent.com/32392878/89047482-09fc6800-d381-11ea-922e-fc1a98ccb800.png)

我到ubuntu上又运行了一遍，这是访问的效果，我本地win去访问xxx.xxx.xx.xx:3000，访问无效果的截图如下
![image](https://user-images.githubusercontent.com/32392878/89047665-4c25a980-d381-11ea-9507-b34a4915b189.png)

**Comment by wmathor** [comment]
这个应该没报错吧，毕竟我对这个一点都不了解，直接按照您说的步骤运行了一下
![image](https://user-images.githubusercontent.com/32392878/89047819-88590a00-d381-11ea-847d-4251192b9e41.png)

控制台貌似是报错了

![image](https://user-images.githubusercontent.com/32392878/89048114-f271af00-d381-11ea-8238-48fdafb8bf60.png)

**Comment by NightCatSama** [comment]
https://github.com/NightCatSama/NightCAT-ChatRoom/blob/e9211c879f139309e5248b1e8b5ff47c7ab56e39/views/register.ejs#L109

改成 console.log(error) 看看控制台里错误是什么

**Comment by wmathor** [comment]
![image](https://user-images.githubusercontent.com/32392878/89051142-631aca80-d386-11ea-95f6-1e6e090769ad.png)

**Comment by NightCatSama** [comment]
看起来像是后端代码的错误，四五年前的项目了，记不太清了

**Comment by wmathor** [comment]
好吧，那就算了，还是非常感谢您及时回复我
